### PR TITLE
Implement file server & software updater

### LINKED ISSUE #4: Implement the firmware update command
Migrated from https://github.com/UAVCAN/pyuavcan/issues/56

### PR DESCRIPTION
**Pull request by pavel-kirienko**
Install this branch for testing:

    pip install git+https://github.com/UAVCAN/yakut@bootloader

How to use it:

- https://github.com/UAVCAN/yakut/blob/bootloader/README.md#updating-node-software
- `yakut file-server --help`

It is better to run it with `--verbose` to see how decisions are made under the hood.

Fixes #4

### CODE REVIEW

**Comment by davidbitton** [comment]
Can I use this to add an  addt'l step to the Ardupilot build process script(s)? Currently, `waf` has the --upload option, but that's only for USB connected devices. Thanks.

**Comment by pavel-kirienko** [comment]
Sure. You will need to alter the build system to make it generate binary files following the naming convention expected by this tool (a compatible naming convention is also used by the PX4 bootloader). After the output is generated, you launch the tool and make it distribute the new binary to the node(s).

You could also keep the tool running in the background continuously (launched like `yakut file-server --plug-and-play=allocation.db --update-software /path/to/build/outputs`) but in this case you will need to manually power cycle your nodes to trigger the check.

**Comment by davidbitton** [comment]
@pavel-kirienko i wasn't aware that a node checks for new firmware on startup. Is that in AP_Periph or is that in the Zubax hardware?

**Comment by pavel-kirienko** [comment]
The check is done by this tool, not the node.

**Pull request merged**
